"""Program phase labels — maps tier to phase name per program."""

PROGRAM_PHASES = {
    "military_prep": {
        "bronze": "Phase 1: Orientation",
        "silver": "Phase 2: Knowledge",
        "gold": "Phase 3: Standards",
        "platinum": "Phase 4: Technical",
        "diamond": "Phase 5: Decision",
        "ironforged": "Completion",
    },
    "earn_car": {
        "bronze": "Phase 1: Vehicle Literacy",
        "silver": "Phase 2: Care & Maintenance",
        "gold": "Phase 3: Legal Preparation & Permit",
        "platinum": "Phase 4: Licensure & Independence",
        "diamond": "Early Purchase Path",
        "ooh_shiny": "Capstone: Full 7-Year Streak",
    },
    "311_civic": {
        "bronze": "Phase 1: Awareness",
        "silver": "Phase 2: Engagement",
        "gold": "Phase 3: Service",
        "platinum": "Phase 4: Leadership",
        "diamond": "Completion",
    },
    "marriage_catholic": {
        "bronze": "Phase 1: Discernment",
        "silver": "Phase 2: Formal Preparation",
        "gold": "Phase 3: Sacramental Preparation",
        "platinum": "Phase 4: Covenant",
        "covenant": "Completion",
    },
    "marriage_secular": {
        "bronze": "Phase 1: Self-Assessment",
        "silver": "Phase 2: Couple Assessment",
        "gold": "Phase 3: Framework Building",
        "platinum": "Phase 4: Commitment",
        "covenant": "Completion",
    },
    "fitness": {
        "bronze": "Weekly Activity",
        "silver": "Assessments & Milestones",
        "gold": "Advanced Fitness",
        "platinum": "Completion",
    },
    "catholic_practices": {
        "bronze": "Weekly Devotion",
        "silver": "Periodic Practices & Study",
        "gold": "Service & Formation",
        "diamond": "Research",
        "legendary": "Endurance Trial",
        "covenant": "Vocation",
    },
    "formation_study": {
        "bronze": "Concrete Circles & Life Sections",
        "silver": "Family, Kin & Local Belonging",
        "gold": "Institutions, Nation & Civic Responsibility",
        "platinum": "Civilization, Humanity & Highest Horizon",
        "diamond": "Synthesis & Teaching Others",
    },
    "summer_capstone": {
        "bronze": "Early Fairness Practice",
        "silver": "Structured Source Finding",
        "gold": "Evidence & Public Narrative Review",
        "platinum": "Legal Standards & Full Record Review",
        "diamond": "Capstone Presentation & Teaching",
    },
    "jury_case_review": {
        "bronze": "Foundation: Fairness & Evidence",
        "gold": "Analysis: Cases, Sources & Narrative",
        "platinum": "Advanced: Legal Standards & Institutional Trust",
        "diamond": "Capstone: Full Packet, Teaching & Named Cases",
    },
    "civic_chain_of_command": {
        "bronze": "Phase 1: Name the Layers",
        "silver": "Phase 2: Full Chain-of-Command Map",
        "gold": "Phase 3: Election Mechanics & Party Pathways",
        "platinum": "Phase 4: Deep Dives & Summer Capstones",
        "diamond": "Phase 5: Election Readiness Capstone",
        "obsidian": "Post-18: Participation & Teaching",
    },
    "revolutionary_minds": {
        "bronze": "Orientation & Wandering",
        "silver": "Summer Immersion",
        "gold": "Optional Depth & Comparison",
        "platinum": "Synthesis & Patterns",
        "diamond": "Application & Teaching",
    },
    "ten_commandments": {
        "bronze": "Learn & Memorize",
        "silver": "Deep Study & Self-Examination",
        "gold": "Applied Ethics",
        "platinum": "Leadership & Teaching",
    },
    "foreign_influence": {
        "bronze": "Foundations: Advertising & Honesty",
        "silver": "Media Literacy & Source Analysis",
        "gold": "Election Security & Case Studies",
        "platinum": "Public Policy & Institutional Defense",
        "diamond": "Teaching & Stewardship",
    },
    "sportsmanship": {
        "bronze": "What Makes a Game a Game",
        "silver": "Lose Well, Read the Room",
        "gold": "Compete Under Pressure",
        "platinum": "Lead, Organize, Coach",
        "diamond": "The Full Arc",
    },
    "creative_writing": {
        "bronze": "Foundation",
        "silver": "Development",
        "gold": "Decisions & Consequences",
        "platinum": "Final Project",
    },
}
