"""Topic banks for research bounties (saint, paradox, effect)."""

RESEARCH_TOPICS = {
    "saint": [
        "St. Maximilian Kolbe",
        "St. Joan of Arc",
        "St. Augustine",
        "St. Thomas Aquinas",
        "St. Francis of Assisi",
        "St. Teresa of Calcutta",
        "St. Patrick",
        "St. Ignatius of Loyola",
        "St. Thérèse of Lisieux",
        "St. Thomas More",
        "St. Padre Pio",
        "St. John Paul II",
        "St. Kateri Tekakwitha",
        "St. Josephine Bakhita",
        "St. Edith Stein",
    ],
    "paradox": [
        "Freedom and Discipline",
        "Forgiveness and Memory",
        "Mercy and Justice",
        "Authority and Accountability",
        "Tradition and Reform",
        "Skepticism and Wonder",
        "Obedience and Conscience",
        "Wealth and Dependency",
        "Peace and Strength",
        "Leaving and Returning",
    ],
    "effect": [
        "Pygmalion Effect",
        "Compound Effect",
        "Butterfly Effect",
        "Network Effect",
        "Matthew Effect",
        "Streisand Effect",
        "Cobra Effect",
        "Dunning-Kruger Effect",
        "Bystander Effect",
        "Halo Effect",
        "Sunk Cost Effect",
        "Moral Hazard",
        "Incentive Effect",
        "Corruption Effect",
        "Silence Effect",
    ],
    "sin": [
        "Pride (Superbia) — opposed by Humility",
        "Greed (Avaritia) — opposed by Generosity",
        "Lust (Luxuria) — opposed by Chastity",
        "Envy (Invidia) — opposed by Kindness",
        "Gluttony (Gula) — opposed by Temperance",
        "Wrath (Ira) — opposed by Patience",
        "Sloth (Acedia) — opposed by Diligence",
    ],
}
