"""Seed data from the life plan docs - milestones per pillar by age band."""

MILESTONES = {
    "spiritual": [
        # Age 0-5: Foundation
        {"age_band": "0-5", "title": "Family prayers", "category": "Foundation"},
        {"age_band": "0-5", "title": "Church attendance", "category": "Foundation"},
        {"age_band": "0-5", "title": "Bible stories", "category": "Foundation"},
        {"age_band": "0-5", "title": "Learn gratitude", "category": "Foundation"},
        {"age_band": "0-5", "title": "Learn forgiveness", "category": "Foundation"},
        # Age 6-12: Exploration
        {"age_band": "6-12", "title": "Read children's Bible", "category": "Exploration"},
        {"age_band": "6-12", "title": "Memorize key verses", "category": "Exploration"},
        {"age_band": "6-12", "title": "Learn church history basics", "category": "Exploration"},
        {"age_band": "6-12", "title": "Learn major world religions", "category": "Exploration"},
        # Age 13-18: Formation
        {"age_band": "13-18", "title": "Theology discussions", "category": "Formation"},
        {"age_band": "13-18", "title": "Apologetics", "category": "Formation"},
        {"age_band": "13-18", "title": "Ethics", "category": "Formation"},
        {"age_band": "13-18", "title": "Volunteer service", "category": "Formation"},
        # Age 18-25: Launch
        {"age_band": "18-25", "title": "Independent church participation", "category": "Launch"},
        {"age_band": "18-25", "title": "Mission/service opportunities", "category": "Launch"},
        {"age_band": "18-25", "title": "Study competing worldviews", "category": "Launch"},
        {"age_band": "18-25", "title": "Develop personal convictions", "category": "Launch"},
        # Age 25-35: Consolidation/Stewardship
        {"age_band": "25-35", "title": "Examined convictions", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Mentorship of others", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Spiritual leadership", "category": "Stewardship"},
    ],
    "financial": [
        {"age_band": "0-5", "title": "529 Plan opened", "category": "Foundation"},
        {"age_band": "0-5", "title": "UTMA/UGMA custodial brokerage opened (parent-managed)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Savings jar system (Spend/Save/Invest)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Connect brands to businesses — companies make things you use", "category": "Foundation"},
        {"age_band": "6-12", "title": "Compound interest understood (penny doubling story)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Show account statements, graph growth together", "category": "Exploration"},
        {"age_band": "6-12", "title": "Youth savings account", "category": "Exploration"},
        {"age_band": "6-12", "title": "Understand what a stock IS (ownership)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Understand what a bond IS (loan)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Understand what an index fund IS (basket of stocks)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Paper trading / stock market game", "category": "Exploration"},
        {"age_band": "13-18", "title": "Sector research and reading basic financials", "category": "Formation"},
        {"age_band": "13-18", "title": "Pick 1–2 stocks together, buy in custodial account", "category": "Formation"},
        {"age_band": "13-18", "title": "Understand risk/reward and index vs. individual stocks", "category": "Formation"},
        {"age_band": "13-18", "title": "Portfolio allocation and diversification", "category": "Formation"},
        {"age_band": "13-18", "title": "Expense ratios and dollar-cost averaging", "category": "Formation"},
        {"age_band": "13-18", "title": "Tax implications of investments", "category": "Formation"},
        {"age_band": "13-18", "title": "First earned income", "category": "Formation"},
        {"age_band": "13-18", "title": "Custodial Roth IRA opened (requires earned income)", "category": "Formation"},
        {"age_band": "13-18", "title": "Budget basics", "category": "Formation"},
        {"age_band": "18-25", "title": "Roth IRA strategy and asset allocation by age", "category": "Launch"},
        {"age_band": "18-25", "title": "Market cycles — understand bull/bear/correction", "category": "Launch"},
        {"age_band": "18-25", "title": "Behavioral finance — why people panic-sell", "category": "Launch"},
        {"age_band": "18-25", "title": "First independent budget", "category": "Launch"},
        {"age_band": "18-25", "title": "Credit literacy", "category": "Launch"},
        {"age_band": "25-35", "title": "Positive net worth", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Investment strategy solidified", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Tax-loss harvesting", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Real estate investment literacy", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Alternative investments understood", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Financial independence trajectory", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Generational wealth structures", "category": "Stewardship"},
    ],
    "education": [
        {"age_band": "0-5", "title": "Expose, don't direct", "category": "Foundation"},
        {"age_band": "0-5", "title": "Track interests (Science, Art, Building, Reading, Nature, Athletics)", "category": "Foundation"},
        {"age_band": "6-12", "title": "Favorite subjects identified", "category": "Exploration"},
        {"age_band": "6-12", "title": "Clubs & competitions", "category": "Exploration"},
        {"age_band": "6-12", "title": "Projects completed", "category": "Exploration"},
        {"age_band": "13-18", "title": "Aptitudes assessed (Math, Writing, Leadership, Mechanical, Social, Creative)", "category": "Formation"},
        {"age_band": "13-18", "title": "Job shadowing", "category": "Formation"},
        {"age_band": "13-18", "title": "Volunteering", "category": "Formation"},
        {"age_band": "13-18", "title": "Internships / Summer camps", "category": "Formation"},
        {"age_band": "13-18", "title": "Academic planning for career goals", "category": "Formation"},
        {"age_band": "18-25", "title": "Degree / Trade / Military / Entrepreneurship path chosen", "category": "Launch"},
        {"age_band": "18-25", "title": "Certifications obtained", "category": "Launch"},
        {"age_band": "25-35", "title": "Career establishment & specialization", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Mastery & mentorship of others", "category": "Stewardship"},
    ],
    "character": [
        {"age_band": "0-5", "title": "Responsibility — make bed, keep commitments", "category": "Foundation"},
        {"age_band": "0-5", "title": "Honesty", "category": "Foundation"},
        {"age_band": "0-5", "title": "Kindness", "category": "Foundation"},
        {"age_band": "6-12", "title": "Courage — admit mistakes, speak honestly", "category": "Exploration"},
        {"age_band": "6-12", "title": "Discipline — delay gratification, finish hard things", "category": "Exploration"},
        {"age_band": "6-12", "title": "Compassion — care for others, volunteer", "category": "Exploration"},
        {"age_band": "6-12", "title": "Keep commitments", "category": "Exploration"},
        {"age_band": "6-12", "title": "Case study: introduce first figure — what they faced, what they chose", "category": "Exploration"},
        {"age_band": "13-18", "title": "Integrity under peer pressure", "category": "Formation"},
        {"age_band": "13-18", "title": "Self-regulation", "category": "Formation"},
        {"age_band": "13-18", "title": "Handle criticism constructively", "category": "Formation"},
        {"age_band": "13-18", "title": "Case study: compare two figures on same issue (e.g., MLK vs. Malcolm X)", "category": "Formation"},
        {"age_band": "13-18", "title": "Case study: Daryl Davis — engaging the enemy with presence", "category": "Formation"},
        {"age_band": "13-18", "title": "Case study: David Goggins — discipline as forge vs. self-destruction", "category": "Formation"},
        {"age_band": "13-18", "title": "Sacramental ladder analysis of a public figure", "category": "Formation"},
        {"age_band": "18-25", "title": "Accountability", "category": "Launch"},
        {"age_band": "18-25", "title": "Resilience", "category": "Launch"},
        {"age_band": "18-25", "title": "Moral reasoning", "category": "Launch"},
        {"age_band": "18-25", "title": "Case study: Sebastian Junger — tribe, belonging, cost of isolation", "category": "Launch"},
        {"age_band": "18-25", "title": "Independent analysis of any figure without being told what to think", "category": "Launch"},
        {"age_band": "25-35", "title": "Wisdom & judgment", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Self-knowledge", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Character leadership — teaching others", "category": "Stewardship"},
    ],
    "life_skills": [
        {"age_band": "0-5", "title": "Self-care basics & routines", "category": "Foundation"},
        {"age_band": "6-12", "title": "Cooking basics", "category": "Exploration"},
        {"age_band": "6-12", "title": "Cleaning", "category": "Exploration"},
        {"age_band": "6-12", "title": "Organization", "category": "Exploration"},
        {"age_band": "13-18", "title": "Laundry", "category": "Formation"},
        {"age_band": "13-18", "title": "Basic home repairs", "category": "Formation"},
        {"age_band": "13-18", "title": "First aid", "category": "Formation"},
        {"age_band": "13-18", "title": "Driving", "category": "Formation"},
        {"age_band": "13-18", "title": "Cybersecurity & online privacy", "category": "Formation"},
        {"age_band": "13-18", "title": "AI literacy & research skills", "category": "Formation"},
        {"age_band": "18-25", "title": "Taxes", "category": "Launch"},
        {"age_band": "18-25", "title": "Insurance", "category": "Launch"},
        {"age_band": "18-25", "title": "Budget & credit management", "category": "Launch"},
        {"age_band": "18-25", "title": "Emergency preparedness", "category": "Launch"},
        {"age_band": "25-35", "title": "Home ownership literacy", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Legal literacy", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Estate planning", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Community leadership", "category": "Stewardship"},
    ],
    "heritage": [
        {"age_band": "0-5", "title": "Family stories — where did Grandma live?", "category": "Foundation"},
        # Language Comprehension Pathway
        {"age_band": "0-5", "title": "Phonological: consistent target language exposure (30%+ waking hours)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Phonological: babbling/producing target language specific sounds", "category": "Foundation"},
        {"age_band": "0-5", "title": "Phonological: accent integration before critical period (age 7)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Vocabulary: core nouns (body, food, family, animals, home) — receptive + productive", "category": "Foundation"},
        {"age_band": "0-5", "title": "Vocabulary: verbs & actions — responds to commands, 2-word combinations", "category": "Foundation"},
        {"age_band": "0-5", "title": "Grammar: correct word order in target language", "category": "Foundation"},
        {"age_band": "0-5", "title": "Grammar: basic verb conjugation (present tense)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Discourse: turn-taking in conversation in target language", "category": "Foundation"},
        {"age_band": "0-5", "title": "Discourse: simple narration — tells what happened", "category": "Foundation"},
        {"age_band": "0-5", "title": "Pragmatics: basic politeness (please, thank you, greetings)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Pragmatics: knows who speaks which language (code-switching awareness)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Literacy: pre-literacy — recognizes text carries meaning, knows letters", "category": "Foundation"},
        {"age_band": "0-5", "title": "Family roles assigned (primary speaker, reinforcer, immersion source)", "category": "Foundation"},
        # 6-12 Heritage + Language
        {"age_band": "6-12", "title": "Family tree constructed", "category": "Exploration"},
        {"age_band": "6-12", "title": "Migration map started", "category": "Exploration"},
        {"age_band": "6-12", "title": "Artifacts preserved/digitized", "category": "Exploration"},
        {"age_band": "6-12", "title": "Vocabulary: concrete vocabulary (2000+ words across daily domains)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Vocabulary: academic vocabulary — content words for school subjects", "category": "Exploration"},
        {"age_band": "6-12", "title": "Grammar: past tense used correctly in narration", "category": "Exploration"},
        {"age_band": "6-12", "title": "Grammar: subjunctive/conditional mood emerging", "category": "Exploration"},
        {"age_band": "6-12", "title": "Grammar: gender/plural agreement consistent", "category": "Exploration"},
        {"age_band": "6-12", "title": "Discourse: sequenced narration with cause/effect", "category": "Exploration"},
        {"age_band": "6-12", "title": "Discourse: argumentative — states opinion with reasons", "category": "Exploration"},
        {"age_band": "6-12", "title": "Pragmatics: register switching (speaks differently to grandparent vs. cousin)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Pragmatics: humor — understands jokes and wordplay in target language", "category": "Exploration"},
        {"age_band": "6-12", "title": "Literacy: decoding — reads simple sentences, writes words", "category": "Exploration"},
        {"age_band": "6-12", "title": "Literacy: fluency — reads paragraphs, writes sentences correctly", "category": "Exploration"},
        {"age_band": "6-12", "title": "Literacy: comprehension — reads chapter books, infers meaning", "category": "Exploration"},
        # 13-18 Heritage + Language
        {"age_band": "13-18", "title": "Ancestor research — one person per year", "category": "Formation"},
        {"age_band": "13-18", "title": "Faith heritage explored", "category": "Formation"},
        {"age_band": "13-18", "title": "Occupation patterns identified", "category": "Formation"},
        {"age_band": "13-18", "title": "Health/genetic awareness", "category": "Formation"},
        {"age_band": "13-18", "title": "Vocabulary: abstract vocabulary — emotions, philosophy, speculation", "category": "Formation"},
        {"age_band": "13-18", "title": "Vocabulary: technical/professional domain language emerging", "category": "Formation"},
        {"age_band": "13-18", "title": "Grammar: academic grammar — complex sentences, passive voice", "category": "Formation"},
        {"age_band": "13-18", "title": "Grammar: formal register mastered (tú vs. usted)", "category": "Formation"},
        {"age_band": "13-18", "title": "Discourse: expository — explains concepts, teaches others", "category": "Formation"},
        {"age_band": "13-18", "title": "Discourse: persuasive — convinces, negotiates, advocates", "category": "Formation"},
        {"age_band": "13-18", "title": "Pragmatics: cultural scripts — navigates cultural events appropriately", "category": "Formation"},
        {"age_band": "13-18", "title": "Pragmatics: indirect speech — understands hints, implied meaning", "category": "Formation"},
        {"age_band": "13-18", "title": "Literacy: analysis — reads for subtext, writes essays with thesis", "category": "Formation"},
        {"age_band": "13-18", "title": "Literacy: synthesis — reads across sources, writes research pieces", "category": "Formation"},
        # 18-25 Heritage + Language
        {"age_band": "18-25", "title": "Historical context — what events shaped us?", "category": "Launch"},
        {"age_band": "18-25", "title": "Cultural inheritance — what to keep, what to end", "category": "Launch"},
        {"age_band": "18-25", "title": "Lessons purchased by ancestors documented", "category": "Launch"},
        {"age_band": "18-25", "title": "Vocabulary: nuanced/literary — connotation, register, double meaning", "category": "Launch"},
        {"age_band": "18-25", "title": "Discourse: academic/professional — presents, writes papers, conducts meetings", "category": "Launch"},
        {"age_band": "18-25", "title": "Pragmatics: full cultural fluency — navigates any social situation", "category": "Launch"},
        {"age_band": "18-25", "title": "Literacy: mastery — reads literature and technical texts fluently", "category": "Launch"},
        {"age_band": "18-25", "title": "Attrition prevention: maintains 20-30% exposure minimum", "category": "Launch"},
        # 25-35 Heritage + Language
        {"age_band": "25-35", "title": "Responsibility of inheritance accepted", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Active stewardship & preservation", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Legacy creation — what story am I leaving?", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Language transmission — teaching own children, assigning family roles", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Attrition prevention: language remains functional, not sentimental", "category": "Stewardship"},
    ],
    "economy": [
        {"age_band": "0-5", "title": "Tier 0: Citizenship — self-care, respect, family participation", "category": "Foundation"},
        {"age_band": "6-12", "title": "Tier 1: Contribution — household, property, organization", "category": "Exploration"},
        {"age_band": "6-12", "title": "Tier 2: Competence — technical, creative, academic skills", "category": "Exploration"},
        {"age_band": "13-18", "title": "Tier 3: Stewardship — budgeting, planning, leadership", "category": "Formation"},
        {"age_band": "13-18", "title": "Tier 4: Initiative — process improvement, opportunity ID", "category": "Formation"},
        {"age_band": "18-25", "title": "Tier 5: Entrepreneurship — products, services, ventures", "category": "Launch"},
        {"age_band": "0-5", "title": "Eligibility: Character gate maintained", "category": "Foundation"},
        {"age_band": "6-12", "title": "Reputation tracked: reliability, quality, initiative", "category": "Exploration"},
        {"age_band": "13-18", "title": "Reward types expanding: currency → authority → access → responsibility", "category": "Formation"},
    ],
    "resilience": [
        {"age_band": "0-5", "title": "Emotional vocabulary — naming feelings", "category": "Foundation"},
        {"age_band": "0-5", "title": "Model healthy stress response", "category": "Foundation"},
        {"age_band": "6-12", "title": "Some problems are too big to solve alone", "category": "Exploration"},
        {"age_band": "6-12", "title": "Talk about hard days (not just good ones)", "category": "Exploration"},
        {"age_band": "13-18", "title": "Substance culture awareness — every field has one", "category": "Formation"},
        {"age_band": "13-18", "title": "Sustainable vs. unsustainable performance", "category": "Formation"},
        {"age_band": "13-18", "title": "ADAPT framework learned", "category": "Formation"},
        {"age_band": "13-18", "title": "Research failure modes of chosen path", "category": "Formation"},
        {"age_band": "18-25", "title": "Sleep protected as non-negotiable", "category": "Launch"},
        {"age_band": "18-25", "title": "Relationships maintained outside pressure environment", "category": "Launch"},
        {"age_band": "18-25", "title": "Define 'enough' before entering system", "category": "Launch"},
        {"age_band": "18-25", "title": "Exit criteria written before high-pressure entry", "category": "Launch"},
        {"age_band": "25-35", "title": "Annual audit: marriage/health/sleep/identity intact?", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Exit plans maintained for toxic environments", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Mentor younger people on pressure management", "category": "Stewardship"},
    ],
}


MILESTONES["dimensional_navigation"] = [
    # Age 0-5: Foundation
    {"age_band": "0-5", "title": "Object permanence fully developed", "category": "Foundation"},
    {"age_band": "0-5", "title": "Teach: some things exist even when you can't see them (feelings, trust, love)", "category": "Foundation"},
    {"age_band": "0-5", "title": "Cause and effect through play", "category": "Foundation"},
    {"age_band": "0-5", "title": "'What happens next?' questioning habit", "category": "Foundation"},
    {"age_band": "0-5", "title": "Golden Rule introduced: 'How would you feel if someone did that to you?'", "category": "Foundation"},
    {"age_band": "0-5", "title": "Teach: 'You deserve kindness too' — dignity as floor", "category": "Foundation"},
    # Age 6-12: Exploration
    {"age_band": "6-12", "title": "Delayed consequences: 'If you do X today, what happens in a week?'", "category": "Exploration"},
    {"age_band": "6-12", "title": "System thinking basics — family and school as systems", "category": "Exploration"},
    {"age_band": "6-12", "title": "Walls of perception: 'What might I not be seeing?'", "category": "Exploration"},
    {"age_band": "6-12", "title": "Comparative stories from world traditions introduced", "category": "Exploration"},
    {"age_band": "6-12", "title": "First/second order consequences understood", "category": "Exploration"},
    {"age_band": "6-12", "title": "Reciprocity: how actions return to you over time", "category": "Exploration"},
    {"age_band": "6-12", "title": "Circuit breaker: difference between guilt (I did wrong) and shame (I am wrong)", "category": "Exploration"},
    {"age_band": "6-12", "title": "Teach: 'Correction ends. If it never ends, something is wrong.'", "category": "Exploration"},
    # Age 13-18: Formation
    {"age_band": "13-18", "title": "Navigation model introduced: Position, Azimuth, Velocity", "category": "Formation"},
    {"age_band": "13-18", "title": "Radius of influence: first and second order thinking", "category": "Formation"},
    {"age_band": "13-18", "title": "Course correction cost: commitment accumulation understood", "category": "Formation"},
    {"age_band": "13-18", "title": "Horizons of perception: delayed → lifetime", "category": "Formation"},
    {"age_band": "13-18", "title": "Before/During/After Life engagement", "category": "Formation"},
    {"age_band": "13-18", "title": "Comparative civilizational models explored", "category": "Formation"},
    {"age_band": "13-18", "title": "Three-directional Golden Rule: self→others, others→self, self→self", "category": "Formation"},
    {"age_band": "13-18", "title": "Conviction vs. accusation framework applied to relationships", "category": "Formation"},
    {"age_band": "13-18", "title": "Identify abuse patterns: 'Is this forming me or destroying me?'", "category": "Formation"},
    {"age_band": "13-18", "title": "Exit criteria: define non-negotiable boundaries BEFORE pressure arrives", "category": "Formation"},
    # Age 18-25: Launch
    {"age_band": "18-25", "title": "Full navigation framework applied to major decisions", "category": "Launch"},
    {"age_band": "18-25", "title": "Third and fourth order influence awareness", "category": "Launch"},
    {"age_band": "18-25", "title": "Generational horizon: 'What am I building that outlasts me?'", "category": "Launch"},
    {"age_band": "18-25", "title": "Current analysis: identify forces acting on trajectory", "category": "Launch"},
    {"age_band": "18-25", "title": "Presence principle: trajectory recognition in real decisions", "category": "Launch"},
    {"age_band": "18-25", "title": "Reciprocity audit: 'Am I treating others as I want to be treated?'", "category": "Launch"},
    {"age_band": "18-25", "title": "Self-treatment audit: 'Am I accepting treatment I would never impose on someone I love?'", "category": "Launch"},
    {"age_band": "18-25", "title": "Distinguish freely chosen discipline from externally imposed suffering", "category": "Launch"},
    {"age_band": "18-25", "title": "Recognize the Accuser wearing the mask of formation", "category": "Launch"},
    # Age 25-35: Stewardship
    {"age_band": "25-35", "title": "Fifth order influence awareness", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Eternal horizon engagement", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Course correction audit: accumulated constraints assessed", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Teaching the navigation framework to others", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Legacy creation conscious and intentional", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Teach circuit breaker to others — prevent generational abuse transmission", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Model three-directional reciprocity in marriage, parenting, community", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Annual audit: 'Is endurance in any area actually unrecognized destruction?'", "category": "Stewardship"},
]
