"""Seed data from the life plan docs - milestones per pillar by age band."""

MILESTONES = {
    "spiritual": [
        # Age 0-5: Foundation
        {"age_band": "0-5", "title": "Family prayers", "category": "Foundation"},
        {"age_band": "0-5", "title": "Church attendance", "category": "Foundation"},
        {"age_band": "0-5", "title": "Bible stories", "category": "Foundation"},
        # Age 6-12: Exploration
        {"age_band": "6-12", "title": "Read children's Bible", "category": "Exploration"},
        {"age_band": "6-12", "title": "Memorize key verses", "category": "Exploration"},
        {"age_band": "6-12", "title": "Learn church history basics", "category": "Exploration"},
        {"age_band": "13-18", "title": "Learn major world religions", "category": "Formation"},
        # Age 13-18: Formation
        {"age_band": "13-18", "title": "Theology discussions", "category": "Formation"},
        {"age_band": "13-18", "title": "Apologetics", "category": "Formation"},
        {"age_band": "13-18", "title": "Ethics", "category": "Formation"},
        {"age_band": "13-18", "title": "Volunteer service", "category": "Formation"},
        # Age 18-25: Launch
        {"age_band": "18-25", "title": "Independent church participation", "category": "Launch"},
        {"age_band": "18-25", "title": "Mission/service opportunities", "category": "Launch"},
        {"age_band": "18-25", "title": "Study competing worldviews", "category": "Launch"},
        {"age_band": "18-25", "title": "Develop personal convictions", "category": "Launch"},
        # Age 25-35: Consolidation/Stewardship
        {"age_band": "25-35", "title": "Examined convictions", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Mentorship of others", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Spiritual leadership", "category": "Stewardship"},
    ],
    "financial": [
        {"age_band": "0-5", "title": "529 Plan opened", "category": "Foundation"},
        {"age_band": "0-5", "title": "UTMA/UGMA custodial brokerage opened (parent-managed)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Savings jar system (Spend/Save/Invest)", "category": "Foundation"},
        {"age_band": "6-12", "title": "Connect brands to businesses — companies make things you use", "category": "Exploration"},
        {"age_band": "6-12", "title": "Compound interest understood (penny doubling story)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Show account statements, graph growth together", "category": "Exploration"},
        {"age_band": "6-12", "title": "Youth savings account", "category": "Exploration"},
        {"age_band": "6-12", "title": "Understand what a stock IS (ownership)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Understand what a bond IS (loan)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Understand what an index fund IS (basket of stocks)", "category": "Exploration"},
        {"age_band": "13-18", "title": "Paper trading / stock market game", "category": "Formation"},
        {"age_band": "13-18", "title": "Sector research and reading basic financials", "category": "Formation"},
        {"age_band": "13-18", "title": "Pick 1–2 stocks together, buy in custodial account", "category": "Formation"},
        {"age_band": "13-18", "title": "Understand risk/reward and index vs. individual stocks", "category": "Formation"},
        {"age_band": "13-18", "title": "Portfolio allocation and diversification", "category": "Formation"},
        {"age_band": "13-18", "title": "Expense ratios and dollar-cost averaging", "category": "Formation"},
        {"age_band": "18-25", "title": "Tax implications of investments", "category": "Launch"},
        {"age_band": "13-18", "title": "First earned income", "category": "Formation"},
        {"age_band": "13-18", "title": "Custodial Roth IRA opened (requires earned income)", "category": "Formation"},
        {"age_band": "13-18", "title": "Budget basics", "category": "Formation"},
        {"age_band": "18-25", "title": "Roth IRA strategy and asset allocation by age", "category": "Launch"},
        {"age_band": "18-25", "title": "Market cycles — understand bull/bear/correction", "category": "Launch"},
        {"age_band": "18-25", "title": "Behavioral finance — why people panic-sell", "category": "Launch"},
        {"age_band": "18-25", "title": "First independent budget", "category": "Launch"},
        {"age_band": "18-25", "title": "Credit literacy", "category": "Launch"},
        {"age_band": "25-35", "title": "Positive net worth", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Investment strategy solidified", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Tax-loss harvesting", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Real estate investment literacy", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Alternative investments understood", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Financial independence trajectory", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Generational wealth structures", "category": "Stewardship"},
    ],
    "education": [
        {"age_band": "0-5", "title": "Expose, don't direct", "category": "Foundation"},
        {"age_band": "0-5", "title": "Track interests (Science, Art, Building, Reading, Nature, Athletics)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Shows curiosity — asks 'why' and 'how' questions regularly", "category": "Foundation"},
        {"age_band": "0-5", "title": "Listens to a full story read aloud and engages with it", "category": "Foundation"},
        {"age_band": "0-5", "title": "Recognizes letters and numbers; beginning phonics awareness", "category": "Foundation"},
        {"age_band": "0-5", "title": "Sustains attention on a self-chosen activity for 15+ minutes", "category": "Foundation"},
        {"age_band": "6-12", "title": "Favorite subjects identified", "category": "Exploration"},
        {"age_band": "6-12", "title": "Clubs & competitions", "category": "Exploration"},
        {"age_band": "6-12", "title": "Projects completed", "category": "Exploration"},
        {"age_band": "13-18", "title": "Aptitudes assessed (Math, Writing, Leadership, Mechanical, Social, Creative)", "category": "Formation"},
        {"age_band": "13-18", "title": "Job shadowing", "category": "Formation"},
        {"age_band": "13-18", "title": "Volunteering", "category": "Formation"},
        {"age_band": "13-18", "title": "Internships / Summer camps", "category": "Formation"},
        {"age_band": "13-18", "title": "Academic planning for career goals", "category": "Formation"},
        {"age_band": "18-25", "title": "Degree / Trade / Military / Entrepreneurship path chosen", "category": "Launch"},
        {"age_band": "18-25", "title": "Certifications obtained", "category": "Launch"},
        {"age_band": "18-25", "title": "First professional job or meaningful internship in chosen field", "category": "Launch"},
        {"age_band": "18-25", "title": "Demonstrates ability to learn new skills independently (self-directed study)", "category": "Launch"},
        {"age_band": "18-25", "title": "Builds professional network — mentors, peers, industry contacts", "category": "Launch"},
        {"age_band": "18-25", "title": "Can articulate career trajectory: where am I, where am I headed, what's the evidence", "category": "Launch"},
        {"age_band": "25-35", "title": "Career establishment & specialization", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Mastery & mentorship of others", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Recognized competence in field — peers seek your input", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Mentors at least one younger person in your profession or craft", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Continues learning — reads, takes courses, attends conferences, stays current", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Can pivot or adapt if industry shifts — not brittle, not stuck", "category": "Stewardship"},
    ],
    "character": [
        {"age_band": "0-5", "title": "Responsibility — make bed, keep commitments", "category": "Foundation"},
        {"age_band": "0-5", "title": "Honesty", "category": "Foundation"},
        {"age_band": "0-5", "title": "Kindness", "category": "Foundation"},
        {"age_band": "6-12", "title": "Courage — admit mistakes, speak honestly", "category": "Exploration"},
        {"age_band": "6-12", "title": "Discipline — delay gratification, finish hard things", "category": "Exploration"},
        {"age_band": "6-12", "title": "Compassion — care for others, volunteer", "category": "Exploration"},
        {"age_band": "6-12", "title": "Keep commitments", "category": "Exploration"},
        {"age_band": "6-12", "title": "Case study: introduce first figure — what they faced, what they chose", "category": "Exploration"},
        {"age_band": "13-18", "title": "Integrity under peer pressure", "category": "Formation"},
        {"age_band": "13-18", "title": "Self-regulation", "category": "Formation"},
        {"age_band": "13-18", "title": "Handle criticism constructively", "category": "Formation"},
        {"age_band": "13-18", "title": "Case study: compare two figures on same issue (e.g., MLK vs. Malcolm X)", "category": "Formation"},
        {"age_band": "6-12", "title": "Case study: Daryl Davis — engaging the enemy with presence", "category": "Exploration"},
        {"age_band": "13-18", "title": "Case study: David Goggins — discipline as forge vs. self-destruction", "category": "Formation"},
        {"age_band": "13-18", "title": "Sacramental ladder analysis of a public figure", "category": "Formation"},
        {"age_band": "18-25", "title": "Accountability", "category": "Launch"},
        {"age_band": "18-25", "title": "Resilience", "category": "Launch"},
        {"age_band": "18-25", "title": "Moral reasoning", "category": "Launch"},
        {"age_band": "18-25", "title": "Case study: Sebastian Junger — tribe, belonging, cost of isolation", "category": "Launch"},
        {"age_band": "18-25", "title": "Independent analysis of any figure without being told what to think", "category": "Launch"},
        {"age_band": "25-35", "title": "Wisdom & judgment", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Self-knowledge", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Character leadership — teaching others", "category": "Stewardship"},
    ],
    "life_skills": [
        {"age_band": "0-5", "title": "Self-care basics & routines", "category": "Foundation"},
        {"age_band": "0-5", "title": "Speech development: communicates needs clearly with words by age 3", "category": "Foundation"},
        {"age_band": "0-5", "title": "Dresses self (with minimal help by age 4-5)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Uses utensils to feed self, pours from small container", "category": "Foundation"},
        {"age_band": "0-5", "title": "Follows family routine: wake, meals, play, bath, bed without constant prompting", "category": "Foundation"},
        {"age_band": "0-5", "title": "Puts away toys and belongings in designated places", "category": "Foundation"},
        {"age_band": "0-5", "title": "Toilet trained and manages bathroom independently", "category": "Foundation"},
        {"age_band": "0-5", "title": "Knows full name, address, and parent phone number", "category": "Foundation"},
        {"age_band": "0-5", "title": "Separates from parent for school/daycare without prolonged distress", "category": "Foundation"},
        {"age_band": "0-5", "title": "Follows basic classroom rules (sit, listen, wait turn, raise hand)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Helps with simple household tasks (set table, carry items, wipe surfaces)", "category": "Foundation"},
        {"age_band": "6-12", "title": "Cooking basics", "category": "Exploration"},
        {"age_band": "6-12", "title": "Cleaning", "category": "Exploration"},
        {"age_band": "6-12", "title": "Organization", "category": "Exploration"},
        {"age_band": "13-18", "title": "Laundry", "category": "Formation"},
        {"age_band": "13-18", "title": "Basic home repairs", "category": "Formation"},
        {"age_band": "13-18", "title": "First aid", "category": "Formation"},
        {"age_band": "13-18", "title": "Driving", "category": "Formation"},
        {"age_band": "13-18", "title": "Cybersecurity & online privacy", "category": "Formation"},
        {"age_band": "13-18", "title": "AI literacy & research skills", "category": "Formation"},
        {"age_band": "18-25", "title": "Taxes", "category": "Launch"},
        {"age_band": "18-25", "title": "Insurance", "category": "Launch"},
        {"age_band": "18-25", "title": "Budget & credit management", "category": "Launch"},
        {"age_band": "18-25", "title": "Emergency preparedness", "category": "Launch"},
        {"age_band": "25-35", "title": "Home ownership literacy", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Legal literacy", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Estate planning", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Community leadership", "category": "Stewardship"},
    ],
    "heritage": [
        {"age_band": "0-5", "title": "Family stories — where did Grandma live?", "category": "Foundation"},
        # Language Comprehension Pathway
        {"age_band": "0-5", "title": "Phonological: consistent target language exposure (30%+ waking hours)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Phonological: babbling/producing target language specific sounds", "category": "Foundation"},
        {"age_band": "0-5", "title": "Phonological: accent integration before critical period (age 7)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Vocabulary: core nouns (body, food, family, animals, home) — receptive + productive", "category": "Foundation"},
        {"age_band": "0-5", "title": "Vocabulary: verbs & actions — responds to commands, 2-word combinations", "category": "Foundation"},
        {"age_band": "0-5", "title": "Grammar: correct word order in target language", "category": "Foundation"},
        {"age_band": "0-5", "title": "Grammar: basic verb conjugation (present tense)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Discourse: turn-taking in conversation in target language", "category": "Foundation"},
        {"age_band": "0-5", "title": "Discourse: simple narration — tells what happened", "category": "Foundation"},
        {"age_band": "0-5", "title": "Pragmatics: basic politeness (please, thank you, greetings)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Pragmatics: knows who speaks which language (code-switching awareness)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Literacy: pre-literacy — recognizes text carries meaning, knows letters", "category": "Foundation"},
        {"age_band": "0-5", "title": "Family roles assigned (primary speaker, reinforcer, immersion source)", "category": "Foundation"},
        # 6-12 Heritage + Language
        {"age_band": "6-12", "title": "Family tree constructed", "category": "Exploration"},
        {"age_band": "6-12", "title": "Migration map started", "category": "Exploration"},
        {"age_band": "6-12", "title": "Artifacts preserved/digitized", "category": "Exploration"},
        {"age_band": "6-12", "title": "Vocabulary: concrete vocabulary (2000+ words across daily domains)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Vocabulary: academic vocabulary — content words for school subjects", "category": "Exploration"},
        {"age_band": "6-12", "title": "Grammar: past tense used correctly in narration", "category": "Exploration"},
        {"age_band": "6-12", "title": "Grammar: subjunctive/conditional mood emerging", "category": "Exploration"},
        {"age_band": "6-12", "title": "Grammar: gender/plural agreement consistent", "category": "Exploration"},
        {"age_band": "6-12", "title": "Discourse: sequenced narration with cause/effect", "category": "Exploration"},
        {"age_band": "6-12", "title": "Discourse: argumentative — states opinion with reasons", "category": "Exploration"},
        {"age_band": "6-12", "title": "Pragmatics: register switching (speaks differently to grandparent vs. cousin)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Pragmatics: humor — understands jokes and wordplay in target language", "category": "Exploration"},
        {"age_band": "6-12", "title": "Literacy: decoding — reads simple sentences, writes words", "category": "Exploration"},
        {"age_band": "6-12", "title": "Literacy: fluency — reads paragraphs, writes sentences correctly", "category": "Exploration"},
        {"age_band": "6-12", "title": "Literacy: comprehension — reads chapter books, infers meaning", "category": "Exploration"},
        # 13-18 Heritage + Language
        {"age_band": "13-18", "title": "Ancestor research — one person per year", "category": "Formation"},
        {"age_band": "13-18", "title": "Faith heritage explored", "category": "Formation"},
        {"age_band": "13-18", "title": "Occupation patterns identified", "category": "Formation"},
        {"age_band": "13-18", "title": "Health/genetic awareness", "category": "Formation"},
        {"age_band": "13-18", "title": "Vocabulary: abstract vocabulary — emotions, philosophy, speculation", "category": "Formation"},
        {"age_band": "13-18", "title": "Vocabulary: technical/professional domain language emerging", "category": "Formation"},
        {"age_band": "13-18", "title": "Grammar: academic grammar — complex sentences, passive voice", "category": "Formation"},
        {"age_band": "13-18", "title": "Grammar: formal register mastered (tú vs. usted)", "category": "Formation"},
        {"age_band": "13-18", "title": "Discourse: expository — explains concepts, teaches others", "category": "Formation"},
        {"age_band": "13-18", "title": "Discourse: persuasive — convinces, negotiates, advocates", "category": "Formation"},
        {"age_band": "13-18", "title": "Pragmatics: cultural scripts — navigates cultural events appropriately", "category": "Formation"},
        {"age_band": "13-18", "title": "Pragmatics: indirect speech — understands hints, implied meaning", "category": "Formation"},
        {"age_band": "13-18", "title": "Literacy: analysis — reads for subtext, writes essays with thesis", "category": "Formation"},
        {"age_band": "13-18", "title": "Literacy: synthesis — reads across sources, writes research pieces", "category": "Formation"},
        # 18-25 Heritage + Language
        {"age_band": "18-25", "title": "Historical context — what events shaped us?", "category": "Launch"},
        {"age_band": "18-25", "title": "Cultural inheritance — what to keep, what to end", "category": "Launch"},
        {"age_band": "18-25", "title": "Lessons purchased by ancestors documented", "category": "Launch"},
        {"age_band": "18-25", "title": "Vocabulary: nuanced/literary — connotation, register, double meaning", "category": "Launch"},
        {"age_band": "18-25", "title": "Discourse: academic/professional — presents, writes papers, conducts meetings", "category": "Launch"},
        {"age_band": "18-25", "title": "Pragmatics: full cultural fluency — navigates any social situation", "category": "Launch"},
        {"age_band": "18-25", "title": "Literacy: mastery — reads literature and technical texts fluently", "category": "Launch"},
        {"age_band": "18-25", "title": "Attrition prevention: maintains 20-30% exposure minimum", "category": "Launch"},
        # 25-35 Heritage + Language
        {"age_band": "25-35", "title": "Responsibility of inheritance accepted", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Active stewardship & preservation", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Legacy creation — what story am I leaving?", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Language transmission — teaching own children, assigning family roles", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Attrition prevention: language remains functional, not sentimental", "category": "Stewardship"},
    ],
    "economy": [
        {"age_band": "0-5", "title": "Tier 0: Citizenship — self-care, respect, family participation", "category": "Foundation"},
        {"age_band": "6-12", "title": "Tier 1: Contribution — household, property, organization", "category": "Exploration"},
        {"age_band": "6-12", "title": "Tier 2: Competence — technical, creative, academic skills", "category": "Exploration"},
        {"age_band": "13-18", "title": "Tier 3: Stewardship — budgeting, planning, leadership", "category": "Formation"},
        {"age_band": "13-18", "title": "Tier 4: Initiative — process improvement, opportunity ID", "category": "Formation"},
        {"age_band": "18-25", "title": "Tier 5: Entrepreneurship — products, services, ventures", "category": "Launch"},
        {"age_band": "18-25", "title": "Manages personal income independently — budget, save, invest, give", "category": "Launch"},
        {"age_band": "18-25", "title": "Understands employer compensation beyond salary (benefits, equity, retirement match)", "category": "Launch"},
        {"age_band": "18-25", "title": "Negotiates pay or rates based on demonstrated value, not entitlement", "category": "Launch"},
        {"age_band": "25-35", "title": "Builds or contributes to a household economy (shared budget, division of labor, savings goals)", "category": "Stewardship"},
        {"age_band": "25-35", "title": "If parent: designs an age-appropriate economy system for own children", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Understands the difference between earning, owning, and building — actively does all three", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Generates income from more than one source (employment + investment, side income, or ownership)", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Teaches financial discipline to someone younger — passes the system forward", "category": "Stewardship"},
        {"age_band": "0-5", "title": "Eligibility: Character gate maintained", "category": "Foundation"},
        {"age_band": "6-12", "title": "Reputation tracked: reliability, quality, initiative", "category": "Exploration"},
        {"age_band": "13-18", "title": "Reward types expanding: currency → authority → access → responsibility", "category": "Formation"},
    ],
    "resilience": [
        {"age_band": "0-5", "title": "Emotional vocabulary — naming feelings", "category": "Foundation"},
        {"age_band": "0-5", "title": "Model healthy stress response", "category": "Foundation"},
        {"age_band": "0-5", "title": "Tolerates frustration without prolonged meltdown (age-appropriate recovery)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Accepts 'no' and transitions between activities without crisis", "category": "Foundation"},
        {"age_band": "0-5", "title": "Falls down, gets back up — learns that minor pain passes", "category": "Foundation"},
        {"age_band": "0-5", "title": "Sleeps independently through the night (age-appropriate by 3-4)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Asks for help when stuck instead of shutting down", "category": "Foundation"},
        {"age_band": "0-5", "title": "Experiences boredom without requiring constant entertainment", "category": "Foundation"},
        {"age_band": "6-12", "title": "Some problems are too big to solve alone", "category": "Exploration"},
        {"age_band": "6-12", "title": "Talk about hard days (not just good ones)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Handles losing a game or competition without quitting or rage", "category": "Exploration"},
        {"age_band": "6-12", "title": "Recovers from a bad grade or correction without spiraling", "category": "Exploration"},
        {"age_band": "6-12", "title": "Names what they are feeling AND what triggered it", "category": "Exploration"},
        {"age_band": "6-12", "title": "Distinguishes between problems they can solve and problems they need help with", "category": "Exploration"},
        {"age_band": "6-12", "title": "Has a calming strategy they use independently (breathing, walking away, counting)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Completes something hard that took multiple attempts — experiences earned success", "category": "Exploration"},
        {"age_band": "13-18", "title": "Substance culture awareness — every field has one", "category": "Formation"},
        {"age_band": "13-18", "title": "Sustainable vs. unsustainable performance", "category": "Formation"},
        {"age_band": "13-18", "title": "ADAPT framework learned", "category": "Formation"},
        {"age_band": "18-25", "title": "Research failure modes of chosen path", "category": "Launch"},
        {"age_band": "13-18", "title": "Sleep protected as non-negotiable", "category": "Formation"},
        {"age_band": "18-25", "title": "Relationships maintained outside pressure environment", "category": "Launch"},
        {"age_band": "18-25", "title": "Define 'enough' before entering system", "category": "Launch"},
        {"age_band": "18-25", "title": "Exit criteria written before high-pressure entry", "category": "Launch"},
        {"age_band": "25-35", "title": "Annual audit: marriage/health/sleep/identity intact?", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Exit plans maintained for toxic environments", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Mentor younger people on pressure management", "category": "Stewardship"},
    ],
}


MILESTONES["dimensional_navigation"] = [
    # Age 0-5: Foundation
    {"age_band": "0-5", "title": "Object permanence fully developed", "category": "Foundation"},
    {"age_band": "0-5", "title": "Teach: some things exist even when you can't see them (feelings, trust, love)", "category": "Foundation"},
    {"age_band": "0-5", "title": "Cause and effect through play", "category": "Foundation"},
    {"age_band": "0-5", "title": "'What happens next?' questioning habit", "category": "Foundation"},
    {"age_band": "0-5", "title": "Golden Rule introduced: 'How would you feel if someone did that to you?'", "category": "Foundation"},
    {"age_band": "0-5", "title": "Teach: 'You deserve kindness too' — dignity as floor", "category": "Foundation"},
    # Age 6-12: Exploration
    {"age_band": "6-12", "title": "Delayed consequences: 'If you do X today, what happens in a week?'", "category": "Exploration"},
    {"age_band": "6-12", "title": "System thinking basics — family and school as systems", "category": "Exploration"},
    {"age_band": "6-12", "title": "Walls of perception: 'What might I not be seeing?'", "category": "Exploration"},
    {"age_band": "6-12", "title": "Comparative stories from world traditions introduced", "category": "Exploration"},
    {"age_band": "6-12", "title": "First/second order consequences understood", "category": "Exploration"},
    {"age_band": "6-12", "title": "Reciprocity: how actions return to you over time", "category": "Exploration"},
    {"age_band": "6-12", "title": "Circuit breaker: difference between guilt (I did wrong) and shame (I am wrong)", "category": "Exploration"},
    {"age_band": "6-12", "title": "Teach: 'Correction ends. If it never ends, something is wrong.'", "category": "Exploration"},
    # Age 13-18: Formation
    {"age_band": "13-18", "title": "Navigation model introduced: Position, Azimuth, Velocity", "category": "Formation"},
    {"age_band": "13-18", "title": "Radius of influence: first and second order thinking", "category": "Formation"},
    {"age_band": "13-18", "title": "Course correction cost: commitment accumulation understood", "category": "Formation"},
    {"age_band": "13-18", "title": "Horizons of perception: delayed → lifetime", "category": "Formation"},
    {"age_band": "13-18", "title": "Before/During/After Life engagement", "category": "Formation"},
    {"age_band": "13-18", "title": "Comparative civilizational models explored", "category": "Formation"},
    {"age_band": "13-18", "title": "Three-directional Golden Rule: self→others, others→self, self→self", "category": "Formation"},
    {"age_band": "13-18", "title": "Conviction vs. accusation framework applied to relationships", "category": "Formation"},
    {"age_band": "13-18", "title": "Identify abuse patterns: 'Is this forming me or destroying me?'", "category": "Formation"},
    {"age_band": "13-18", "title": "Exit criteria: define non-negotiable boundaries BEFORE pressure arrives", "category": "Formation"},
    # Age 18-25: Launch
    {"age_band": "18-25", "title": "Full navigation framework applied to major decisions", "category": "Launch"},
    {"age_band": "18-25", "title": "Third and fourth order influence awareness", "category": "Launch"},
    {"age_band": "18-25", "title": "Generational horizon: 'What am I building that outlasts me?'", "category": "Launch"},
    {"age_band": "18-25", "title": "Current analysis: identify forces acting on trajectory", "category": "Launch"},
    {"age_band": "18-25", "title": "Presence principle: trajectory recognition in real decisions", "category": "Launch"},
    {"age_band": "18-25", "title": "Reciprocity audit: 'Am I treating others as I want to be treated?'", "category": "Launch"},
    {"age_band": "18-25", "title": "Self-treatment audit: 'Am I accepting treatment I would never impose on someone I love?'", "category": "Launch"},
    {"age_band": "18-25", "title": "Distinguish freely chosen discipline from externally imposed suffering", "category": "Launch"},
    {"age_band": "18-25", "title": "Recognize the Accuser wearing the mask of formation", "category": "Launch"},
    # Age 25-35: Stewardship
    {"age_band": "25-35", "title": "Fifth order influence awareness", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Eternal horizon engagement", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Course correction audit: accumulated constraints assessed", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Teaching the navigation framework to others", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Legacy creation conscious and intentional", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Teach circuit breaker to others — prevent generational abuse transmission", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Model three-directional reciprocity in marriage, parenting, community", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Annual audit: 'Is endurance in any area actually unrecognized destruction?'", "category": "Stewardship"},
]

MILESTONES["civic"] = [
    # Age 0-5: Foundation
    {"age_band": "0-5", "title": "Learns: family is a system with roles and shared responsibilities", "category": "Foundation"},
    {"age_band": "0-5", "title": "Understands: some people have jobs that help the community (firefighters, teachers, doctors)", "category": "Foundation"},
    {"age_band": "0-5", "title": "Introduces: 'Who decides?' questions about everyday rules", "category": "Foundation"},
    {"age_band": "0-5", "title": "Parents must know where the child is — no exceptions", "category": "Foundation"},
    {"age_band": "0-5", "title": "Unsafe secrets are not allowed — difference between surprise and secrecy", "category": "Foundation"},
    {"age_band": "0-5", "title": "Gifts from adults should be known by parents", "category": "Foundation"},
    # Age 6-12: Exploration
    {"age_band": "6-12", "title": "Layers of governance: self → family → community → local → state → national", "category": "Exploration"},
    {"age_band": "6-12", "title": "Voting beyond elections: money, time, attention, purchases are all 'votes'", "category": "Exploration"},
    {"age_band": "6-12", "title": "Local institutions identified: school board, town council, churches, community orgs", "category": "Exploration"},
    {"age_band": "6-12", "title": "Ownership basics: what does it mean to own part of a business (stocks)?", "category": "Exploration"},
    {"age_band": "6-12", "title": "Owning the means of production: buying stock = owning the factory, not just buying its products", "category": "Exploration"},
    {"age_band": "6-12", "title": "Power of time: compound interest, skill development, institutional growth", "category": "Exploration"},
    {"age_band": "6-12", "title": "Civic symbol literacy: reads first political cartoon — 'What is this saying about power?'", "category": "Exploration"},
    {"age_band": "6-12", "title": "Rules exist for reasons — cheating harms trust", "category": "Exploration"},
    {"age_band": "6-12", "title": "Groups can pressure people to do wrong", "category": "Exploration"},
    {"age_band": "6-12", "title": "Gifts can create obligation — the favor trap introduced", "category": "Exploration"},
    {"age_band": "6-12", "title": "'Don't tell' pressure is a warning sign", "category": "Exploration"},
    # Age 13-18: Formation
    {"age_band": "13-18", "title": "Visibility problem: most influence is local/invisible, not presidential/celebrity", "category": "Formation"},
    {"age_band": "13-18", "title": "How local government actually works: attends or watches a council/board meeting", "category": "Formation"},
    {"age_band": "13-18", "title": "Economic participation: understands shareholders, dividends, capital allocation", "category": "Formation"},
    {"age_band": "13-18", "title": "Ownership vs. employment: the difference between working for vs. owning productive assets", "category": "Formation"},
    {"age_band": "13-18", "title": "Stock market as means of production: anyone can own the companies that make, ship, and sell — not just the wealthy", "category": "Formation"},
    {"age_band": "13-18", "title": "Long-term ownership: early investment + time + dividends reinvested = compounding ownership stake", "category": "Formation"},
    {"age_band": "13-18", "title": "Civic symbol literacy: analyzes propaganda, ads, memes, speeches for power structures", "category": "Formation"},
    {"age_band": "13-18", "title": "Identifies: 'Who benefits if the crowd keeps moving?' in public messaging", "category": "Formation"},
    {"age_band": "13-18", "title": "Institutional awareness: which institutions shape daily life beyond government?", "category": "Formation"},
    {"age_band": "13-18", "title": "Distributed influence: understands that a crowd's participation sustains authority", "category": "Formation"},
    {"age_band": "13-18", "title": "Difference between individual crime and organized crime as a system", "category": "Formation"},
    {"age_band": "13-18", "title": "How corruption hides inside legitimate institutions — the respectable mask", "category": "Formation"},
    {"age_band": "13-18", "title": "How blackmail, debt, addiction, and shame can control people", "category": "Formation"},
    {"age_band": "13-18", "title": "Following the money: high-level money-flow concepts", "category": "Formation"},
    {"age_band": "13-18", "title": "'Everyone does it' is a warning sign, not permission", "category": "Formation"},
    {"age_band": "13-18", "title": "Evaluates claims of corruption using evidence — not paranoia, not denial", "category": "Formation"},
    # Age 18-25: Launch
    {"age_band": "18-25", "title": "Votes in elections with understanding of local, state, and national layers", "category": "Launch"},
    {"age_band": "18-25", "title": "Investment as participation: builds portfolio as ownership stake in productive systems", "category": "Launch"},
    {"age_band": "18-25", "title": "Organizational influence: joins or builds organizations (professional, civic, religious)", "category": "Launch"},
    {"age_band": "18-25", "title": "Institutional criticism → stewardship: moves from 'this is broken' to 'how do I fix it?'", "category": "Launch"},
    {"age_band": "18-25", "title": "Can articulate how influence flows through any system they participate in", "category": "Launch"},
    {"age_band": "18-25", "title": "Civic symbol literacy: detects narrative framing in news, corporate messaging, political speech", "category": "Launch"},
    {"age_band": "18-25", "title": "Workplace ethics and conflicts of interest understood", "category": "Launch"},
    {"age_band": "18-25", "title": "Recognizes how social circles normalize wrongdoing", "category": "Launch"},
    {"age_band": "18-25", "title": "Refuses opportunities that require secrecy, lying, or moral compromise", "category": "Launch"},
    # Age 25-35: Stewardship
    {"age_band": "25-35", "title": "Institutional stewardship: supports, reforms, or creates institutions", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Civilizational influence: contributes ideas, structures, or traditions that persist beyond self", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Teaches civic/institutional navigation to others", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Asks: 'Which institutions deserve support? Reform? Creation?'", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Understands society as something they actively shape, not something happening to them", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Builds clean financial and professional records — avoids compromised networks", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Recognizes captured systems — supports accountability without mob behavior", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Leaves cleaner institutions than were inherited", "category": "Stewardship"},
]

MILESTONES["scientific_reality_testing"] = [
    # Age 0-5: Foundation — Notice reality
    {"age_band": "0-5", "title": "Uses senses to observe the world", "category": "Foundation"},
    {"age_band": "0-5", "title": "Learns cause and effect through play", "category": "Foundation"},
    {"age_band": "0-5", "title": "'What happened?' before 'Why?'", "category": "Foundation"},
    {"age_band": "0-5", "title": "Object permanence: things exist even when unseen", "category": "Foundation"},
    {"age_band": "0-5", "title": "Emotional labeling: 'I feel' versus 'It is'", "category": "Foundation"},
    {"age_band": "0-5", "title": "Simple prediction: 'What happens next?'", "category": "Foundation"},
    {"age_band": "0-5", "title": "Sorting and comparing", "category": "Foundation"},
    {"age_band": "0-5", "title": "Mistakes are information, not shame", "category": "Foundation"},
    # Age 6-12: Exploration — Ask and test
    {"age_band": "6-12", "title": "Learns basic scientific method vocabulary", "category": "Exploration"},
    {"age_band": "6-12", "title": "Conducts simple experiments", "category": "Exploration"},
    {"age_band": "6-12", "title": "Records observations", "category": "Exploration"},
    {"age_band": "6-12", "title": "Distinguishes observation from explanation", "category": "Exploration"},
    {"age_band": "6-12", "title": "Fair test concept: change one thing at a time", "category": "Exploration"},
    {"age_band": "6-12", "title": "Repeated results matter", "category": "Exploration"},
    {"age_band": "6-12", "title": "Basic data tracking", "category": "Exploration"},
    {"age_band": "6-12", "title": "Compares claims from books, adults, media, and experience", "category": "Exploration"},
    {"age_band": "6-12", "title": "'I don't know yet' as a valid answer", "category": "Exploration"},
    {"age_band": "6-12", "title": "Introspective experiments: habits, study, sleep, chores, emotions", "category": "Exploration"},
    # Age 13-18: Formation — Test models
    {"age_band": "13-18", "title": "Understands hypothesis, evidence, variable, correlation, causation", "category": "Formation"},
    {"age_band": "13-18", "title": "Learns confirmation bias and motivated reasoning", "category": "Formation"},
    {"age_band": "13-18", "title": "Tests study methods and personal routines", "category": "Formation"},
    {"age_band": "13-18", "title": "Evaluates health, money, media, and political claims", "category": "Formation"},
    {"age_band": "13-18", "title": "Learns evidence hierarchy", "category": "Formation"},
    {"age_band": "13-18", "title": "Distinguishes scientific from moral/spiritual/philosophical claims", "category": "Formation"},
    {"age_band": "13-18", "title": "Practices changing belief without shame", "category": "Formation"},
    {"age_band": "13-18", "title": "Identity should not fuse with hypothesis", "category": "Formation"},
    {"age_band": "13-18", "title": "Formal reflection logs: belief, evidence, test, revision", "category": "Formation"},
    # Age 18-25: Launch — Use evidence for life decisions
    {"age_band": "18-25", "title": "Treats major plans as testable models", "category": "Launch"},
    {"age_band": "18-25", "title": "Tracks finances, health, study, work, relationships, spiritual practices", "category": "Launch"},
    {"age_band": "18-25", "title": "Understands limits of anecdote and base rates", "category": "Launch"},
    {"age_band": "18-25", "title": "Detects manipulation through fake statistics or selective evidence", "category": "Launch"},
    {"age_band": "18-25", "title": "Applies scientific thinking to career, investing, civic claims", "category": "Launch"},
    {"age_band": "18-25", "title": "Can explain why science and religion need not be enemies", "category": "Launch"},
    {"age_band": "18-25", "title": "Annual reality audit: believed vs. happened vs. changed", "category": "Launch"},
    # Age 25-35: Stewardship — Teach and govern with reality testing
    {"age_band": "25-35", "title": "Uses evidence in parenting, marriage, work, money, civic life", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Builds systems that can be evaluated and improved", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Avoids ideological capture by preferred theories", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Teaches children how to observe, test, and revise", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Uses data without dehumanizing people", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Reviews long-term life hypotheses against lived outcomes", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Capable of saying: 'I was wrong, and here is what I changed'", "category": "Stewardship"},
    # Lost Knowledge addendum milestones integrated
    {"age_band": "6-12", "title": "Learns simple examples of knowledge rediscovery", "category": "Exploration"},
    {"age_band": "6-12", "title": "Learns that old knowledge can be useful or wrong", "category": "Exploration"},
    {"age_band": "13-18", "title": "Studies examples of delayed scientific acceptance", "category": "Formation"},
    {"age_band": "13-18", "title": "Absence of evidence vs. evidence of absence", "category": "Formation"},
    {"age_band": "13-18", "title": "Learns why charlatans thrive when serious inquiry fails", "category": "Formation"},
    {"age_band": "18-25", "title": "Evaluates controversial claims using evidence categories", "category": "Launch"},
    {"age_band": "18-25", "title": "Studies institutional incentives and resistance to correction", "category": "Launch"},
    {"age_band": "25-35", "title": "Builds family and institutional memory against knowledge decay", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Distinguishes mystery from fraud, humility from cowardice", "category": "Stewardship"},
]

MILESTONES["inheritance_burden_stewardship"] = [
    # Age 0-5: Foundation — The child receives before understanding
    {"age_band": "0-5", "title": "Experiences stable family care", "category": "Foundation"},
    {"age_band": "0-5", "title": "Learns family names and relationships", "category": "Foundation"},
    {"age_band": "0-5", "title": "Begins hearing family stories", "category": "Foundation"},
    {"age_band": "0-5", "title": "Objects, people, and promises continue over time", "category": "Foundation"},
    {"age_band": "0-5", "title": "Simple gratitude practices begun", "category": "Foundation"},
    {"age_band": "0-5", "title": "Actions affect others", "category": "Foundation"},
    # Age 6-12: Exploration — Family has history
    {"age_band": "6-12", "title": "Learns basic family tree", "category": "Exploration"},
    {"age_band": "6-12", "title": "Learns family places and migrations", "category": "Exploration"},
    {"age_band": "6-12", "title": "Money inheritance concepts: saving, wasting, preserving", "category": "Exploration"},
    {"age_band": "6-12", "title": "Families pass down good and bad habits", "category": "Exploration"},
    {"age_band": "6-12", "title": "Previous generations made choices that affect today", "category": "Exploration"},
    {"age_band": "6-12", "title": "Gratitude without pretending everything was good", "category": "Exploration"},
    # Age 13-18: Formation — Inheritance includes burden
    {"age_band": "13-18", "title": "Studies family financial patterns", "category": "Formation"},
    {"age_band": "13-18", "title": "Civic duties and public debt understood at age-appropriate level", "category": "Formation"},
    {"age_band": "13-18", "title": "Wars and political decisions impose costs on later generations", "category": "Formation"},
    {"age_band": "13-18", "title": "Institutions can protect or exploit", "category": "Formation"},
    {"age_band": "13-18", "title": "Elder authority honored but not treated as infallible", "category": "Formation"},
    {"age_band": "13-18", "title": "Identifies family patterns worth preserving or ending", "category": "Formation"},
    {"age_band": "13-18", "title": "Difference between fault, responsibility, control, and response", "category": "Formation"},
    # Age 18-25: Launch — Taking custody of inheritance
    {"age_band": "18-25", "title": "Reviews inherited assets and liabilities", "category": "Launch"},
    {"age_band": "18-25", "title": "Independent financial and civic decisions begun", "category": "Launch"},
    {"age_band": "18-25", "title": "Studies family medical, financial, and relational risks", "category": "Launch"},
    {"age_band": "18-25", "title": "Builds personal estate and moral legacy", "category": "Launch"},
    {"age_band": "18-25", "title": "Challenges inherited assumptions respectfully", "category": "Launch"},
    {"age_band": "18-25", "title": "Refuses destructive patterns without contempt", "category": "Launch"},
    {"age_band": "18-25", "title": "Contributes to institutions instead of merely criticizing", "category": "Launch"},
    # Age 25-35: Stewardship — Becomes a transmitter
    {"age_band": "25-35", "title": "Builds inheritance for future children or dependents", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Preserves records, wealth, stories, and wisdom", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Repairs family patterns where possible", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Participates responsibly in civic and institutional life", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Long-term decisions with descendants in mind", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Teaches next generation to audit inheritance without bitterness", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Leaves clearer maps than were received", "category": "Stewardship"},
    # Recidivism/Forgiveness addendum milestones integrated
    {"age_band": "0-5", "title": "Hurt can be named and repaired", "category": "Foundation"},
    {"age_band": "6-12", "title": "Forgiveness and trust are different things", "category": "Exploration"},
    {"age_band": "6-12", "title": "Repeated behavior matters — memory can protect", "category": "Exploration"},
    {"age_band": "13-18", "title": "Recidivism: repeated harmful patterns reveal trajectory", "category": "Formation"},
    {"age_band": "13-18", "title": "Distinguishes reconciliation from pressure to 'move on'", "category": "Formation"},
    {"age_band": "18-25", "title": "Sets boundaries without hatred — evidence-based restoration only", "category": "Launch"},
    {"age_band": "25-35", "title": "Prevents unsafe restoration; mercy, truth, memory coexist", "category": "Stewardship"},
]

MILESTONES["catholic_formation"] = [
    # Age 0-5: Foundation — Receives faith before understanding
    {"age_band": "0-5", "title": "Baptism completed and recorded", "category": "Foundation"},
    {"age_band": "0-5", "title": "Godparents selected and documented", "category": "Foundation"},
    {"age_band": "0-5", "title": "Baptism certificate stored", "category": "Foundation"},
    {"age_band": "0-5", "title": "Sunday Mass rhythm established", "category": "Foundation"},
    {"age_band": "0-5", "title": "Sign of the Cross learned", "category": "Foundation"},
    {"age_band": "0-5", "title": "Simple prayers learned", "category": "Foundation"},
    {"age_band": "0-5", "title": "Blessings experienced at home", "category": "Foundation"},
    {"age_band": "0-5", "title": "Sacred images and symbols introduced", "category": "Foundation"},
    {"age_band": "0-5", "title": "Advent, Christmas, Lent, Easter traditions started", "category": "Foundation"},
    {"age_band": "0-5", "title": "Safe-environment basics: trusted adults, body boundaries, no unsafe secrets", "category": "Foundation"},
    # Age 6-12: Exploration — Sacramental preparation and moral awakening
    {"age_band": "6-12", "title": "Age-appropriate examination of conscience learned", "category": "Exploration"},
    {"age_band": "6-12", "title": "Prepares for First Reconciliation", "category": "Exploration"},
    {"age_band": "6-12", "title": "Receives First Reconciliation", "category": "Exploration"},
    {"age_band": "6-12", "title": "Prepares for First Holy Communion", "category": "Exploration"},
    {"age_band": "6-12", "title": "Receives First Holy Communion", "category": "Exploration"},
    {"age_band": "6-12", "title": "Reverence for the Eucharist learned", "category": "Exploration"},
    {"age_band": "6-12", "title": "Basic structure of the Mass learned", "category": "Exploration"},
    {"age_band": "6-12", "title": "Ten Commandments at age-appropriate level", "category": "Exploration"},
    {"age_band": "6-12", "title": "Saints studied as real models", "category": "Exploration"},
    {"age_band": "6-12", "title": "Simple works of mercy begun", "category": "Exploration"},
    {"age_band": "6-12", "title": "Questions about suffering, death, heaven, hell engaged", "category": "Exploration"},
    # Age 13-18: Formation — Confirmation, discernment, tested faith
    {"age_band": "13-18", "title": "Confirmation preparation begun", "category": "Formation"},
    {"age_band": "13-18", "title": "Confirmation sponsor chosen", "category": "Formation"},
    {"age_band": "13-18", "title": "Confirmation saint chosen", "category": "Formation"},
    {"age_band": "13-18", "title": "Confirmation received", "category": "Formation"},
    {"age_band": "13-18", "title": "Gifts and fruits of the Holy Spirit learned", "category": "Formation"},
    {"age_band": "13-18", "title": "Catholic Social Teaching learned", "category": "Formation"},
    {"age_band": "13-18", "title": "Church history studied honestly (saints, failures, reform, scandal)", "category": "Formation"},
    {"age_band": "13-18", "title": "Distinguishes doctrine, discipline, culture, opinion, and abuse of authority", "category": "Formation"},
    {"age_band": "13-18", "title": "Practices confession as healing rather than humiliation", "category": "Formation"},
    {"age_band": "13-18", "title": "Spiritual discernment practiced (friends, media, habits, vocation)", "category": "Formation"},
    # Age 18-25: Launch — Adult Catholic responsibility
    {"age_band": "18-25", "title": "Chooses parish or campus ministry independently", "category": "Launch"},
    {"age_band": "18-25", "title": "Maintains Mass attendance by personal conviction", "category": "Launch"},
    {"age_band": "18-25", "title": "Maintains confession rhythm", "category": "Launch"},
    {"age_band": "18-25", "title": "Develops personal prayer rule", "category": "Launch"},
    {"age_band": "18-25", "title": "Studies Catechism or structured Catholic doctrine", "category": "Launch"},
    {"age_band": "18-25", "title": "Discerns vocation seriously (marriage, priesthood, religious life, single life)", "category": "Launch"},
    {"age_band": "18-25", "title": "Understands dating through sacramental vocation lens", "category": "Launch"},
    {"age_band": "18-25", "title": "Stays Catholic amid institutional disappointment", "category": "Launch"},
    # Age 25-35: Stewardship — Vocation, transmission
    {"age_band": "25-35", "title": "Lives chosen vocation with seriousness", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Catholic household rhythm built (if parent)", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Practices hospitality, mercy, and service", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Develops ability to teach faith to children or younger people", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Preserves sacramental records for next generation", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Audits Catholic inheritance: what was received, neglected, repaired", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Breaks patterns of neglect, hypocrisy, or performative religion", "category": "Stewardship"},
    # Recidivism/Forgiveness addendum milestones integrated
    {"age_band": "6-12", "title": "Learns that saying sorry does not erase hurt instantly", "category": "Exploration"},
    {"age_band": "13-18", "title": "Learns how institutions can misuse forgiveness language", "category": "Formation"},
    {"age_band": "18-25", "title": "Practices mature apology and restitution", "category": "Launch"},
    {"age_band": "25-35", "title": "Teaches forgiveness without naivety — protects vulnerable", "category": "Stewardship"},
]

MILESTONES["secular_sacred_formation"] = [
    # Age 0-5: Foundation — Receives formation before belief questions arise
    {"age_band": "0-5", "title": "Experiences ritual, blessing, and family traditions", "category": "Foundation"},
    {"age_band": "0-5", "title": "Learns gratitude practices (secular or sacred)", "category": "Foundation"},
    {"age_band": "0-5", "title": "Learns that actions have consequences beyond self", "category": "Foundation"},
    {"age_band": "0-5", "title": "Experiences community belonging through shared meals/events", "category": "Foundation"},
    {"age_band": "0-5", "title": "Learns basic repair: 'What do we do when we hurt someone?'", "category": "Foundation"},
    # Age 6-12: Exploration — Civilizational literacy begins
    {"age_band": "6-12", "title": "Learns that different cultures have creation stories and origin accounts", "category": "Exploration"},
    {"age_band": "6-12", "title": "Understands sacrifice as giving something up so others may benefit", "category": "Exploration"},
    {"age_band": "6-12", "title": "Learns basic authority literacy: who may teach, command, forgive?", "category": "Exploration"},
    {"age_band": "6-12", "title": "Learns that rituals help communities remember", "category": "Exploration"},
    {"age_band": "6-12", "title": "Asks: 'What human problem was this tradition trying to solve?'", "category": "Exploration"},
    {"age_band": "6-12", "title": "Learns death is real and cultures handle it differently", "category": "Exploration"},
    # Age 13-18: Formation — Sacred literacy without forced belief
    {"age_band": "13-18", "title": "Studies origin questions: creation, cosmology, evolution, simulation", "category": "Formation"},
    {"age_band": "13-18", "title": "Studies sacrifice across civilizations (Eucharist, scapegoating, martyrdom)", "category": "Formation"},
    {"age_band": "13-18", "title": "Distinguishes believing a doctrine from understanding it", "category": "Formation"},
    {"age_band": "13-18", "title": "Learns repentance/accountability in secular and religious forms", "category": "Formation"},
    {"age_band": "13-18", "title": "Authority audit: which authorities do I recognize and why?", "category": "Formation"},
    {"age_band": "13-18", "title": "Studies historical conversions, reversions, apostasy, and return", "category": "Formation"},
    {"age_band": "13-18", "title": "Learns that doubt can be inquiry, not identity", "category": "Formation"},
    # Age 18-25: Launch — Formation persists through unbelief
    {"age_band": "18-25", "title": "Can articulate what doctrines address even without believing them", "category": "Launch"},
    {"age_band": "18-25", "title": "Practices moral repair (accountability, amends, restitution) without religion", "category": "Launch"},
    {"age_band": "18-25", "title": "Understands belonging: family, nation, tradition, humanity", "category": "Launch"},
    {"age_band": "18-25", "title": "Recognizes false substitutes for religion (ideology, consumerism, nihilism)", "category": "Launch"},
    {"age_band": "18-25", "title": "Keeps the road home visible — return remains possible", "category": "Launch"},
    {"age_band": "18-25", "title": "Audit: what survives disbelief? What would make return possible?", "category": "Launch"},
    # Age 25-35: Stewardship — Transmission without coercion
    {"age_band": "25-35", "title": "Can teach civilizational literacy to younger people", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Preserves formation even when personal belief is uncertain", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Does not burn bridges home for self or children", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Practices gratitude, reverence, moral repair without requiring certainty", "category": "Stewardship"},
    {"age_band": "25-35", "title": "Understands what ancestors understood and what they failed to explain", "category": "Stewardship"},
    # Recidivism/Forgiveness addendum milestones integrated
    {"age_band": "6-12", "title": "Learns that forgiveness does not mean forgetting or re-access", "category": "Exploration"},
    {"age_band": "13-18", "title": "Patterns reveal trajectory — repeated harm is not an isolated event", "category": "Formation"},
    {"age_band": "18-25", "title": "Recognizes when 'move on' is coercion vs. genuine mercy", "category": "Launch"},
    {"age_band": "25-35", "title": "Builds systems where mercy, truth, memory, and protection coexist", "category": "Stewardship"},
]
