"""Seed data from the life plan docs - milestones per pillar by age band."""

MILESTONES = {
    "spiritual": [
        # Age 0-5: Foundation
        {"age_band": "0-5", "title": "Family prayers", "category": "Foundation"},
        {"age_band": "0-5", "title": "Church attendance", "category": "Foundation"},
        {"age_band": "0-5", "title": "Bible stories", "category": "Foundation"},
        {"age_band": "0-5", "title": "Learn gratitude", "category": "Foundation"},
        {"age_band": "0-5", "title": "Learn forgiveness", "category": "Foundation"},
        # Age 6-12: Exploration
        {"age_band": "6-12", "title": "Read children's Bible", "category": "Exploration"},
        {"age_band": "6-12", "title": "Memorize key verses", "category": "Exploration"},
        {"age_band": "6-12", "title": "Learn church history basics", "category": "Exploration"},
        {"age_band": "6-12", "title": "Learn major world religions", "category": "Exploration"},
        # Age 13-18: Formation
        {"age_band": "13-18", "title": "Theology discussions", "category": "Formation"},
        {"age_band": "13-18", "title": "Apologetics", "category": "Formation"},
        {"age_band": "13-18", "title": "Ethics", "category": "Formation"},
        {"age_band": "13-18", "title": "Volunteer service", "category": "Formation"},
        # Age 18-25: Launch
        {"age_band": "18-25", "title": "Independent church participation", "category": "Launch"},
        {"age_band": "18-25", "title": "Mission/service opportunities", "category": "Launch"},
        {"age_band": "18-25", "title": "Study competing worldviews", "category": "Launch"},
        {"age_band": "18-25", "title": "Develop personal convictions", "category": "Launch"},
        # Age 25-35: Consolidation/Stewardship
        {"age_band": "25-35", "title": "Examined convictions", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Mentorship of others", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Spiritual leadership", "category": "Stewardship"},
    ],
    "financial": [
        {"age_band": "0-5", "title": "529 Plan opened", "category": "Foundation"},
        {"age_band": "0-5", "title": "UTMA/UGMA custodial brokerage opened (parent-managed)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Savings jar system (Spend/Save/Invest)", "category": "Foundation"},
        {"age_band": "0-5", "title": "Connect brands to businesses — companies make things you use", "category": "Foundation"},
        {"age_band": "6-12", "title": "Compound interest understood (penny doubling story)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Show account statements, graph growth together", "category": "Exploration"},
        {"age_band": "6-12", "title": "Youth savings account", "category": "Exploration"},
        {"age_band": "6-12", "title": "Understand what a stock IS (ownership)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Understand what a bond IS (loan)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Understand what an index fund IS (basket of stocks)", "category": "Exploration"},
        {"age_band": "6-12", "title": "Paper trading / stock market game", "category": "Exploration"},
        {"age_band": "13-18", "title": "Sector research and reading basic financials", "category": "Formation"},
        {"age_band": "13-18", "title": "Pick 1–2 stocks together, buy in custodial account", "category": "Formation"},
        {"age_band": "13-18", "title": "Understand risk/reward and index vs. individual stocks", "category": "Formation"},
        {"age_band": "13-18", "title": "Portfolio allocation and diversification", "category": "Formation"},
        {"age_band": "13-18", "title": "Expense ratios and dollar-cost averaging", "category": "Formation"},
        {"age_band": "13-18", "title": "Tax implications of investments", "category": "Formation"},
        {"age_band": "13-18", "title": "First earned income", "category": "Formation"},
        {"age_band": "13-18", "title": "Custodial Roth IRA opened (requires earned income)", "category": "Formation"},
        {"age_band": "13-18", "title": "Budget basics", "category": "Formation"},
        {"age_band": "18-25", "title": "Roth IRA strategy and asset allocation by age", "category": "Launch"},
        {"age_band": "18-25", "title": "Market cycles — understand bull/bear/correction", "category": "Launch"},
        {"age_band": "18-25", "title": "Behavioral finance — why people panic-sell", "category": "Launch"},
        {"age_band": "18-25", "title": "First independent budget", "category": "Launch"},
        {"age_band": "18-25", "title": "Credit literacy", "category": "Launch"},
        {"age_band": "25-35", "title": "Positive net worth", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Investment strategy solidified", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Tax-loss harvesting", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Real estate investment literacy", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Alternative investments understood", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Financial independence trajectory", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Generational wealth structures", "category": "Stewardship"},
    ],
    "education": [
        {"age_band": "0-5", "title": "Expose, don't direct", "category": "Foundation"},
        {"age_band": "0-5", "title": "Track interests (Science, Art, Building, Reading, Nature, Athletics)", "category": "Foundation"},
        {"age_band": "6-12", "title": "Favorite subjects identified", "category": "Exploration"},
        {"age_band": "6-12", "title": "Clubs & competitions", "category": "Exploration"},
        {"age_band": "6-12", "title": "Projects completed", "category": "Exploration"},
        {"age_band": "13-18", "title": "Aptitudes assessed (Math, Writing, Leadership, Mechanical, Social, Creative)", "category": "Formation"},
        {"age_band": "13-18", "title": "Job shadowing", "category": "Formation"},
        {"age_band": "13-18", "title": "Volunteering", "category": "Formation"},
        {"age_band": "13-18", "title": "Internships / Summer camps", "category": "Formation"},
        {"age_band": "13-18", "title": "Academic planning for career goals", "category": "Formation"},
        {"age_band": "18-25", "title": "Degree / Trade / Military / Entrepreneurship path chosen", "category": "Launch"},
        {"age_band": "18-25", "title": "Certifications obtained", "category": "Launch"},
        {"age_band": "25-35", "title": "Career establishment & specialization", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Mastery & mentorship of others", "category": "Stewardship"},
    ],
    "character": [
        {"age_band": "0-5", "title": "Responsibility — make bed, keep commitments", "category": "Foundation"},
        {"age_band": "0-5", "title": "Honesty", "category": "Foundation"},
        {"age_band": "0-5", "title": "Kindness", "category": "Foundation"},
        {"age_band": "6-12", "title": "Courage — admit mistakes, speak honestly", "category": "Exploration"},
        {"age_band": "6-12", "title": "Discipline — delay gratification, finish hard things", "category": "Exploration"},
        {"age_band": "6-12", "title": "Compassion — care for others, volunteer", "category": "Exploration"},
        {"age_band": "6-12", "title": "Keep commitments", "category": "Exploration"},
        {"age_band": "6-12", "title": "Case study: introduce first figure — what they faced, what they chose", "category": "Exploration"},
        {"age_band": "13-18", "title": "Integrity under peer pressure", "category": "Formation"},
        {"age_band": "13-18", "title": "Self-regulation", "category": "Formation"},
        {"age_band": "13-18", "title": "Handle criticism constructively", "category": "Formation"},
        {"age_band": "13-18", "title": "Case study: compare two figures on same issue (e.g., MLK vs. Malcolm X)", "category": "Formation"},
        {"age_band": "13-18", "title": "Case study: Daryl Davis — engaging the enemy with presence", "category": "Formation"},
        {"age_band": "13-18", "title": "Case study: David Goggins — discipline as forge vs. self-destruction", "category": "Formation"},
        {"age_band": "13-18", "title": "Sacramental ladder analysis of a public figure", "category": "Formation"},
        {"age_band": "18-25", "title": "Accountability", "category": "Launch"},
        {"age_band": "18-25", "title": "Resilience", "category": "Launch"},
        {"age_band": "18-25", "title": "Moral reasoning", "category": "Launch"},
        {"age_band": "18-25", "title": "Case study: Sebastian Junger — tribe, belonging, cost of isolation", "category": "Launch"},
        {"age_band": "18-25", "title": "Independent analysis of any figure without being told what to think", "category": "Launch"},
        {"age_band": "25-35", "title": "Wisdom & judgment", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Self-knowledge", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Character leadership — teaching others", "category": "Stewardship"},
    ],
    "life_skills": [
        {"age_band": "0-5", "title": "Self-care basics & routines", "category": "Foundation"},
        {"age_band": "6-12", "title": "Cooking basics", "category": "Exploration"},
        {"age_band": "6-12", "title": "Cleaning", "category": "Exploration"},
        {"age_band": "6-12", "title": "Organization", "category": "Exploration"},
        {"age_band": "13-18", "title": "Laundry", "category": "Formation"},
        {"age_band": "13-18", "title": "Basic home repairs", "category": "Formation"},
        {"age_band": "13-18", "title": "First aid", "category": "Formation"},
        {"age_band": "13-18", "title": "Driving", "category": "Formation"},
        {"age_band": "13-18", "title": "Cybersecurity & online privacy", "category": "Formation"},
        {"age_band": "13-18", "title": "AI literacy & research skills", "category": "Formation"},
        {"age_band": "18-25", "title": "Taxes", "category": "Launch"},
        {"age_band": "18-25", "title": "Insurance", "category": "Launch"},
        {"age_band": "18-25", "title": "Budget & credit management", "category": "Launch"},
        {"age_band": "18-25", "title": "Emergency preparedness", "category": "Launch"},
        {"age_band": "25-35", "title": "Home ownership literacy", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Legal literacy", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Estate planning", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Community leadership", "category": "Stewardship"},
    ],
    "heritage": [
        {"age_band": "0-5", "title": "Family stories — where did Grandma live?", "category": "Foundation"},
        {"age_band": "6-12", "title": "Family tree constructed", "category": "Exploration"},
        {"age_band": "6-12", "title": "Migration map started", "category": "Exploration"},
        {"age_band": "6-12", "title": "Language fragments understood", "category": "Exploration"},
        {"age_band": "6-12", "title": "Artifacts preserved/digitized", "category": "Exploration"},
        {"age_band": "13-18", "title": "Ancestor research — one person per year", "category": "Formation"},
        {"age_band": "13-18", "title": "Faith heritage explored", "category": "Formation"},
        {"age_band": "13-18", "title": "Occupation patterns identified", "category": "Formation"},
        {"age_band": "13-18", "title": "Health/genetic awareness", "category": "Formation"},
        {"age_band": "18-25", "title": "Historical context — what events shaped us?", "category": "Launch"},
        {"age_band": "18-25", "title": "Cultural inheritance — what to keep, what to end", "category": "Launch"},
        {"age_band": "18-25", "title": "Lessons purchased by ancestors documented", "category": "Launch"},
        {"age_band": "25-35", "title": "Responsibility of inheritance accepted", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Active stewardship & preservation", "category": "Stewardship"},
        {"age_band": "25-35", "title": "Legacy creation — what story am I leaving?", "category": "Stewardship"},
    ],
    "economy": [
        {"age_band": "0-5", "title": "Tier 0: Citizenship — self-care, respect, family participation", "category": "Foundation"},
        {"age_band": "6-12", "title": "Tier 1: Contribution — household, property, organization", "category": "Exploration"},
        {"age_band": "6-12", "title": "Tier 2: Competence — technical, creative, academic skills", "category": "Exploration"},
        {"age_band": "13-18", "title": "Tier 3: Stewardship — budgeting, planning, leadership", "category": "Formation"},
        {"age_band": "13-18", "title": "Tier 4: Initiative — process improvement, opportunity ID", "category": "Formation"},
        {"age_band": "18-25", "title": "Tier 5: Entrepreneurship — products, services, ventures", "category": "Launch"},
        {"age_band": "0-5", "title": "Eligibility: Character gate maintained", "category": "Foundation"},
        {"age_band": "6-12", "title": "Reputation tracked: reliability, quality, initiative", "category": "Exploration"},
        {"age_band": "13-18", "title": "Reward types expanding: currency → authority → access → responsibility", "category": "Formation"},
    ],
    "resilience": [
        {"age_band": "0-5", "title": "Emotional vocabulary — naming feelings", "category": "Foundation"},
        {"age_band": "0-5", "title": "Model healthy stress response", "category": "Foundation"},
        {"age_band": "6-12", "title": "Some problems are too big to solve alone", "category": "Exploration"},
        {"age_band": "6-12", "title": "Talk about hard days (not just good ones)", "category": "Exploration"},
        {"age_band": "13-18", "title": "Substance culture awareness — every field has one", "category": "Formation"},
        {"age_band": "13-18", "title": "Sustainable vs. unsustainable performance", "category": "Formation"},
        {"age_band": "13-18", "title": "ADAPT framework learned", "category": "Formation"},
        {"age_band": "13-18", "title": "Research failure modes of chosen path", "category": "Formation"},
        {"age_band": "18-25", "title": "Sleep protected as non-negotiable", "category": "Launch"},
        {"age_band": "18-25", "title": "Relationships maintained outside pressure environment", "category": "Launch"},
        {"age_band": "18-25", "title": "Define 'enough' before entering system", "category": "Launch"},
        {"age_band": "18-25", "title": "Exit criteria written before high-pressure entry", "category": "Launch"},
        {"age_band": "25-35", "title": "Annual audit: marriage/health/sleep/identity intact?", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Exit plans maintained for toxic environments", "category": "Consolidation"},
        {"age_band": "25-35", "title": "Mentor younger people on pressure management", "category": "Stewardship"},
    ],
}
